version: '3'

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
    driver: local

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.1
    environment:
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"
    networks:
      - elk
    ports:
      - "9200:9200"
    restart: unless-stopped
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.2.1
    depends_on:
      - elasticsearch
    networks:
      - elk
    ports:
      - "5044:5044"
    restart: unless-stopped
    volumes:
      - ./etc/logstash/pipeline:/usr/share/logstash/pipeline:ro

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.1
    depends_on:
      - elasticsearch
    environment:
      - "ELASTICSEARCH_PASSWORD=changeme"
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
      - "ELASTICSEARCH_USERNAME=elastic"
    networks:
      - elk
    ports:
      - "5601:5601"
    restart: unless-stopped
