name: Auto Assign

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
    - uses: kentaro-m/auto-assign-action@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        assignees: 'your-github-username'
        issue-message: "Hey @phantom0004, you have a new issue to look at!"
        pr-message: "Hey @phantom0004, you have a new pull request to review!"
